---
title: "Visualizations"
author: "Elena Rein"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(maps)  
library(mapproj) 
library(gganimate)
library(usmap)
```
 
# Map overall trend of healthy and unhealthy food access at county level 

```{r}
clean_data <- read.csv("~/Desktop/Data Science/Midterm Project/full_data_2011_2016.csv")
clean_data %>% 
  mutate(countystate = paste(county, state_full)) -> clean_data
```
 

## Bring in coordinate data 

```{r}
us_counties <- map_data("county")
us_counties <- us_counties %>% 
  mutate(state_full = str_to_title(region)) %>% 
  mutate(county = str_to_title(subregion)) %>% 
  mutate(countystate = paste(county, state_full))
```

## Subset to 2011 only 

```{r}
clean_data_2011 <- clean_data %>% 
  filter(!is.na(year)) %>% 
  filter(year == 2011)
```

```{r}
clean_data_2011 %>% 
  arrange(desc(unhealthy_per10000))
```

```{r}
clean_data_2011 %>% 
  arrange(desc(healthy_per10000))
```


## Join with the coordinate data 

```{r}
left_join(us_counties, clean_data_2011, by = "countystate") -> clean_data_2011_latlong
```

## Remove outlier, plot unhealthy sources per 10,000 people 

```{r 07-maps-8, fig.cap='Mapping the results', out.width="100%", fig.width=6, fig.height=5}
clean_data_2011_latlong %>%
  filter(countystate != "San Juan Colorado") %>% 
  filter(state != "HI") %>% 
  filter(state != "AK") %>% 
    ggplot(aes(x = long, y = lat, 
               group = group, fill = unhealthy_per10000)) +
    geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) + 
  scale_fill_continuous(low = "white", high = "blue")
```

## Remove outlier, plot healthy sources per 10,000 people 

```{r 07-maps-8, fig.cap='Mapping the results', out.width="100%", fig.width=6, fig.height=5}
clean_data_2011_latlong %>%
  filter(state != "HI") %>% 
  filter(state != "AK") %>% 
    ggplot(aes(x = long, y = lat, 
               group = group, fill = healthy_per10000)) +
    geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) + 
  scale_fill_continuous(low = "white", high = "green")
```

